### ISSUE TITLE
Working with Eur version?

### ISSUE THREAD

**Issue by krzys837** [wagrenier/Obscura#10]
Hello.
It is working with European FF1 version?
I can't make it work even with cmd.
Drag and drop iso on .exe don't work too.

**Comment by HikikoMarmy** [comment]
As of version 0.0.3, the extractor relies on an external json for file lookup. It isn't included in the release download, so you will have to get it from the resource folder here: https://github.com/wagrenier/Obscura/tree/main/resource

Place the json in the same folder as the executable, and it should extract files for the EU version correctly :)

**Comment by krzys837** [comment]
Well. It's works, thank you.  Maybe it's should be put in readme or something.
By the way. Is there a chance to repack these files?

**Comment by HikikoMarmy** [comment]
Glad that you got it resolved!
The file dictionary will be included in the release build to avoid this issue in the future, and we'll work on a readme!

Right now there isn't any way to repack these files wholly, at least not with Obscura. In the future there may be features to repack game files, but it needs more research.

**Comment by krzys837** [comment]
Very thank you for respondings! :)
